import type { ProgramCatalogEntry, ProgramSlug } from '@/types/content';

export const PROGRAM_METADATA: Record<ProgramSlug, ProgramCatalogEntry> = {
  six_day_reset: {
    slug: 'six_day_reset',
    name: '6-Day Control',
    description: 'A focused six-day reset that interrupts autopilot and builds immediate control.',
    totalDays: 6,
    category: 'smoking',
    hasAudio: false,
    contentStatus: 'sample',
  },
  ninety_day_transform: {
    slug: 'ninety_day_transform',
    name: '90-Day Smoking Reset',
    description: 'A long-form smoking recovery path with daily reflection and guided audio.',
    totalDays: 90,
    category: 'smoking',
    hasAudio: true,
    contentStatus: 'sample',
  },
  sleep_disorder_reset: {
    slug: 'sleep_disorder_reset',
    name: '21-Day Deep Sleep Reset',
    description: 'A structured sleep-support program with daily text and guided sleep audio.',
    totalDays: 21,
    category: 'sleep',
    hasAudio: true,
    contentStatus: 'ready',
  },
  energy_vitality: {
    slug: 'energy_vitality',
    name: '14-Day Energy Restore',
    description: 'A program focused on restoring energy, rhythm, and daily momentum.',
    totalDays: 14,
    category: 'energy',
    hasAudio: false,
    contentStatus: 'placeholder',
  },
  age_reversal: {
    slug: 'age_reversal',
    name: '90-Day Biohacking Reset',
    description: 'A longevity-focused program with daily facial exercises, circulation walks, and calm recovery.',
    totalDays: 90,
    category: 'aging',
    hasAudio: false,
    contentStatus: 'ready',
  },
  male_sexual_health: {
    slug: 'male_sexual_health',
    name: "30-Day Men's Vitality Reset",
    description: 'A confidence and regulation program with shared CALM support.',
    totalDays: 30,
    category: 'sexual_health',
    hasAudio: false,
    contentStatus: 'placeholder',
  },
};
